### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by eduarddotgg** [kristoferjoseph/postcss-modular-scale#18]
This is my postcss config:

``` js
var postcssPlugins = [
    stylelint({
        configFile: './.stylelintrc'
    })
    , reporter({clearMessages: true})
    , cssInject({
        injectTo: 'fileStart',
        cssFilePath: 'src/_css-variables.css'
    })
    , mscale
    , vars
    , nested
    , minmax
    , customMedia
    , grid({separator: '--'})
    , autoprefixer
];
```

This is my css:

``` css
.copyrights {
    display: block;
    opacity: .3;
    font-size: ms(.8)rem;

    @media screen and (min-width: 640px){
        font-size: ms(1)rem;
    }
}
```

the problem appears when i add nested media query.

This injects with postcss-inject to the begging of css file

``` css
:root {
    --ms-bases: 1, .6;
    --ms-ratios: 1.414;
}
```

This troughs error too:

``` css
.copyrights {
    display: block;
    opacity: .3;
    font-size: ms(.8)rem;
}

@media screen and (min-width: 640px){
    .copyrights {
        font-size: ms(1)rem;
    }
}
```
