### ISSUE TITLE
Not using the defined variable.

### ISSUE THREAD

**Issue by janwirth** [kristoferjoseph/postcss-modular-scale#24]
I am using this module with the spike build system. Spike uses SugarSS by default.

When I try to change the ratios it has no effect.

``` css
:root
  --ms-bases: 1, 0.75
  --ms-ratios: 1.2

h2
  ms: var(--ms-ratios) // 1.2
  font-size: ms(1)em // 1.618em
```

Any idea on how to resolve this?

**Comment by lkraav** [comment]
I'm seeing the same thing.

**Comment by mrmartineau** [comment]
@kristoferjoseph have you had a chance to look into this? I am also experiencing a similar problem: no matter what values I choose for the `--ms-bases` and `--ms-ratios` variables, the output is always the same. I am happy to help you debug this but I am brand new to PostCSS so might need some help? 

With these settings:
```css
:root {
	--ms-bases: 20;
	--ms-ratios: 1.125;
}

.foo {
	bases: var(--ms-bases);
	ratios: var(--ms-ratios);
	ms1: ms(1);
	ms2: ms(2);
}
```
I get this output:

```css
.foo {
	bases: 20;
	ratios: 1.125;
	ms1: 1.618rem;
	ms2: 2.618rem;
}
```

When I should be getting this result:
```css
.foo {
	bases: 20;
	ratios: 1.125;
	ms1: 1.125rem;
	ms2: 1.266rem;
}
```

Are you maintaining this repo anymore?
