### ISSUE TITLE
Using only one base value causes compilation to stop

### ISSUE THREAD

**Issue by lmartins** [kristoferjoseph/postcss-modular-scale#7]
When I try to use only one base value, the compilation never finishes.

``` css
:root {
  --ms-bases: 1.084;
  --ms-ratios: 1;
}
```
